
windowrule {
  name = windowrule-1
  float = on
  move = topright+30
  match:class = ^(org.pulseaudio.pavucontrol)$
}

windowrule {
  name = windowrule-2
  float = on
  move = topright+30
  match:class = ^(org.kde.kalk)$
}


# Ignore maximize requests from apps. You'll probably like this.
windowrule = match:class .*, suppress_event maximize no_initial_focus on

# Fix some dragging issues with XWayland


windowrule {
  name = float-stuff
  match:class = ^(btop|mixer|yay|org.kde.kweather)$
  float = 1
  size = 1000 600
  center = on
}

windowrule {
  name = miniplayer
  match:title = ^(Picture-in-Picture)$
  float = 1
  center = on
  size = 800 600
}

layerrule = match:title wofi, blur 1
layerrule = match:title wofi, ignore_alpha 0
layerrule = match:title waybar, blur 1
layerrule = match:title waybar, ignore_alpha 0
layerrule = match:title swaync-notification-window, blur 1
layerrule = match:title swaync-notification-window, ignore_alpha 0.2
layerrule = match:title swaync-control-center, blur 1
layerrule = match:title swaync-control-center, ignore_alpha 0

